const SCHEDULES_ALLOWED_READ_ROLES = Object.freeze([
  "spocadmin",
  "superadmin",
]);

const DEFAULT_SCHEDULES_PAGE = 1;
const MAX_SCHEDULES_LIMIT = 200;
const DEFAULT_DEPARTMENT_DAY_SLOTS = 12;
const TRAINER_SCHEDULE_DEFAULT_STATUS = "scheduled";
const ASSIGN_SCHEDULE_SUCCESS_MESSAGE = "Schedule assigned successfully";
const ASSIGN_SCHEDULE_NOT_FOUND_MESSAGE = "Schedule not found";
const ASSIGN_SCHEDULE_ERROR_MESSAGE = "Error assigning schedule";
const UPDATE_SCHEDULE_SUCCESS_MESSAGE = "Schedule updated successfully";
const UPDATE_SCHEDULE_NOT_FOUND_MESSAGE = "Schedule not found";
const UPDATE_SCHEDULE_ERROR_MESSAGE = "Failed to update schedule";
const DELETE_SCHEDULE_SUCCESS_MESSAGE = "Schedule deleted successfully";
const DELETE_SCHEDULE_NOT_FOUND_MESSAGE = "Schedule not found";
const DELETE_SCHEDULE_ERROR_MESSAGE = "Failed to delete schedule";
const DELETE_SCHEDULE_DEFAULT_REASON = "Session cancelled by administrator.";
const CREATE_SCHEDULE_SUCCESS_MESSAGE = "Schedule created successfully";
const CREATE_SCHEDULE_ERROR_MESSAGE = "Failed to create schedule";
const BULK_CREATE_SCHEDULE_ERROR_MESSAGE = "Failed to create schedules";
const BULK_CREATE_REQUIRED_ARRAY_MESSAGE = "Schedules array is required";
const BULK_CREATE_EMPTY_RESULT_MESSAGE = "No new schedules to create";
const BULK_UPLOAD_SCHEDULE_ERROR_MESSAGE = "Server error";
const BULK_UPLOAD_SHEET_NAME_MESSAGE = "Sheet name must be 'Schedule'";
const BULK_UPLOAD_NO_FILE_MESSAGE = "No file uploaded";
const BULK_UPLOAD_FILE_ERROR_MESSAGE = "Upload failed";

module.exports = {
  ASSIGN_SCHEDULE_ERROR_MESSAGE,
  ASSIGN_SCHEDULE_NOT_FOUND_MESSAGE,
  ASSIGN_SCHEDULE_SUCCESS_MESSAGE,
  UPDATE_SCHEDULE_ERROR_MESSAGE,
  UPDATE_SCHEDULE_NOT_FOUND_MESSAGE,
  UPDATE_SCHEDULE_SUCCESS_MESSAGE,
  DELETE_SCHEDULE_DEFAULT_REASON,
  DELETE_SCHEDULE_ERROR_MESSAGE,
  DELETE_SCHEDULE_NOT_FOUND_MESSAGE,
  DELETE_SCHEDULE_SUCCESS_MESSAGE,
  CREATE_SCHEDULE_ERROR_MESSAGE,
  CREATE_SCHEDULE_SUCCESS_MESSAGE,
  BULK_CREATE_EMPTY_RESULT_MESSAGE,
  BULK_CREATE_REQUIRED_ARRAY_MESSAGE,
  BULK_CREATE_SCHEDULE_ERROR_MESSAGE,
  BULK_UPLOAD_FILE_ERROR_MESSAGE,
  BULK_UPLOAD_NO_FILE_MESSAGE,
  BULK_UPLOAD_SCHEDULE_ERROR_MESSAGE,
  BULK_UPLOAD_SHEET_NAME_MESSAGE,
  SCHEDULES_ALLOWED_READ_ROLES,
  DEFAULT_SCHEDULES_PAGE,
  MAX_SCHEDULES_LIMIT,
  DEFAULT_DEPARTMENT_DAY_SLOTS,
  TRAINER_SCHEDULE_DEFAULT_STATUS,
};
