const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

function generateReportPDF(data, fileName) {
  return new Promise((resolve, reject) => {
    const tempDir = path.join(__dirname, "../temp");
    fs.mkdirSync(tempDir, { recursive: true });

    const safeFileName = String(fileName || "report.pdf");
    const filePath = path.join(tempDir, safeFileName);

    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    doc
      .fontSize(20)
      .fillColor("#1e3a8a")
      .text("MBK Carriez Report", { align: "center" });

    doc.moveDown();

    doc
      .fontSize(12)
      .fillColor("black")
      .text(`Company: ${data.companyName || "N/A"}`)
      .text(`Date: ${data.date || "N/A"}`)
      .moveDown();

    doc.text(`Total Trainers: ${data.totalTrainers ?? 0}`);
    doc.text(`Active Today: ${data.activeToday ?? 0}`);
    doc.text(`Completed Sessions: ${data.completedSessions ?? 0}`);
    doc.text(`Pending Attendance: ${data.pendingAttendance ?? 0}`);

    doc.moveDown();
    doc.text("Generated by MBK Carriez System");

    doc.end();

    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
  });
}

module.exports = generateReportPDF;
