const CHAT_VALIDATION_LOGS_USER_NOT_FOUND_MESSAGE = "User not found";
const CHAT_VALIDATION_LOGS_FETCH_FAILED_MESSAGE = "Failed to fetch validation logs";
const CHAT_BOOTSTRAP_USER_NOT_FOUND_MESSAGE = "User not found";
const CHAT_CREATE_FAILED_MESSAGE = "Failed to create chat";
const CHAT_CREATE_SUCCESS_MESSAGE = "Chat created";
const CHAT_LIST_FETCH_FAILED_MESSAGE = "Failed to fetch chats";
const CHAT_SEARCH_QUERY_REQUIRED_MESSAGE = "Search query is required";
const CHAT_MESSAGE_SEARCH_QUERY_REQUIRED_MESSAGE = "Search text is required";
const CHAT_MESSAGE_SEARCH_FETCH_FAILED_MESSAGE = "Failed to search messages";
const CHAT_MESSAGE_HISTORY_FETCH_FAILED_MESSAGE = "Failed to fetch message history";
const CHAT_MESSAGE_SEND_SUCCESS_MESSAGE = "Message sent";
const CHAT_MESSAGE_SEND_FAILED_MESSAGE = "Failed to send message";
const CHAT_CHANNEL_AUDIT_LOG_FETCH_FAILED_MESSAGE = "Failed to fetch channel audit log";
const CHAT_INFO_FETCH_FAILED_MESSAGE = "Failed to load chat info";
const CHAT_DELETE_FOR_ME_SUCCESS_MESSAGE = "Message deleted for you";
const CHAT_DELETE_FOR_ME_FAILED_MESSAGE = "Failed to delete message for you";
const CHAT_DELETE_FOR_EVERYONE_SUCCESS_MESSAGE = "Message deleted for everyone";
const CHAT_DELETE_FOR_EVERYONE_FAILED_MESSAGE = "Failed to delete message for everyone";
const CHAT_BROADCAST_USER_NOT_FOUND_MESSAGE = "User not found";
const CHAT_BROADCAST_NO_RECIPIENTS_MESSAGE = "No Trainers/SPOCs available for broadcast";
const CHAT_BROADCAST_INPUT_REQUIRED_MESSAGE = "Announcement text or broadcast name is required";
const CHAT_BROADCAST_RECIPIENT_ROLES = ["Trainer", "SPOCAdmin", "CollegeAdmin"];

module.exports = {
  CHAT_BOOTSTRAP_USER_NOT_FOUND_MESSAGE,
  CHAT_CHANNEL_AUDIT_LOG_FETCH_FAILED_MESSAGE,
  CHAT_CREATE_FAILED_MESSAGE,
  CHAT_CREATE_SUCCESS_MESSAGE,
  CHAT_BROADCAST_INPUT_REQUIRED_MESSAGE,
  CHAT_BROADCAST_NO_RECIPIENTS_MESSAGE,
  CHAT_BROADCAST_RECIPIENT_ROLES,
  CHAT_BROADCAST_USER_NOT_FOUND_MESSAGE,
  CHAT_DELETE_FOR_EVERYONE_FAILED_MESSAGE,
  CHAT_DELETE_FOR_EVERYONE_SUCCESS_MESSAGE,
  CHAT_DELETE_FOR_ME_FAILED_MESSAGE,
  CHAT_DELETE_FOR_ME_SUCCESS_MESSAGE,
  CHAT_INFO_FETCH_FAILED_MESSAGE,
  CHAT_LIST_FETCH_FAILED_MESSAGE,
  CHAT_MESSAGE_HISTORY_FETCH_FAILED_MESSAGE,
  CHAT_MESSAGE_SEND_FAILED_MESSAGE,
  CHAT_MESSAGE_SEND_SUCCESS_MESSAGE,
  CHAT_MESSAGE_SEARCH_FETCH_FAILED_MESSAGE,
  CHAT_MESSAGE_SEARCH_QUERY_REQUIRED_MESSAGE,
  CHAT_SEARCH_QUERY_REQUIRED_MESSAGE,
  CHAT_VALIDATION_LOGS_FETCH_FAILED_MESSAGE,
  CHAT_VALIDATION_LOGS_USER_NOT_FOUND_MESSAGE,
};
